[package]
name = "blake2"
version = "0.3.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "BLAKE2 hash functions"
documentation = "https://docs.rs/blake2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "blake2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
byte-tools = "0.1"
digest = "0.3"
generic-array = "0.5"
crypto-ops = "0.1"
#crypto-mac = {path = "../../../rust-crypto-decoupled/utils/crypto-mac/"}

[dev-dependencies]
crypto-tests = "0.2"
