[package]
name = "blake2"
version = "0.9.0-pre"
description = "BLAKE2 hash functions"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/blake2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "blake2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "= 0.9.0-pre"
byte-tools = "0.3"
byteorder = { version = "1", default-features = false }
crypto-mac = "= 0.8.0-pre"
opaque-debug = "0.2"

[dev-dependencies]
digest = { version = "= 0.9.0-pre", features = ["dev"] }
crypto-mac = { version = "0.8.0-pre", features = ["dev"] }
hex-literal = "0.1"

[features]
default = ["std"]
std = ["digest/std", "byteorder/std", "crypto-mac/std"]
simd = []
simd_opt = ["simd"]
simd_asm = ["simd_opt"]
